/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author reyes
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String usuario;
    String password;

    private DatagramSocket socket;
    Direccion_IP ip = new Direccion_IP();

    public Login() {
        try {
            initComponents();
            setTitle("Sistema Bancario");
            setExtendedState(MAXIMIZED_BOTH);
            txt_Password.requestFocus();

            socket = new DatagramSocket();

        } catch (SocketException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jEImagePanel1 = new LIB.JEImagePanel();
        jPanelTransparente1 = new LIB.JPanelTransparente();
        txt_Usuario = new LIB.JTexfieldPH_FielTex();
        txt_Password = new LIB.JTexfieldPH_Password();
        JPanel_Login = new LIB.JPanelRound();
        JLabel_Login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelTransparente2 = new LIB.JPanelTransparente();
        JLabel_Registro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/city-Paris-Eiffel-Tower-bokeh-Focus-blur-653955-wallhere.com.jpg"))); // NOI18N
        jEImagePanel1.setLayout(new java.awt.GridBagLayout());

        jPanelTransparente1.setColorPrimario(new java.awt.Color(222, 222, 188));
        jPanelTransparente1.setColorSecundario(new java.awt.Color(87, 60, 39));
        jPanelTransparente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Usuario.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_Usuario.setPlaceholder("Usuario:");
        jPanelTransparente1.add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txt_Password.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        txt_Password.setPlaceholder("Contraseña:");
        txt_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PasswordKeyTyped(evt);
            }
        });
        jPanelTransparente1.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        JPanel_Login.setColorPrimario(new java.awt.Color(73, 51, 30));
        JPanel_Login.setColorSecundario(new java.awt.Color(73, 51, 30));
        JPanel_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabel_Login.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        JLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Login.setText("Iniciar Sesion");
        JLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabel_LoginMouseClicked(evt);
            }
        });
        JPanel_Login.add(JLabel_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, 20));

        jPanelTransparente1.add(JPanel_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanelTransparente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema Bancario");
        jPanelTransparente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanelTransparente1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 20));

        jPanelTransparente2.setColorPrimario(new java.awt.Color(73, 51, 30));
        jPanelTransparente2.setColorSecundario(new java.awt.Color(73, 51, 30));

        JLabel_Registro.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        JLabel_Registro.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Registro.setText("Registrar");
        JLabel_Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabel_RegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransparente2Layout = new javax.swing.GroupLayout(jPanelTransparente2);
        jPanelTransparente2.setLayout(jPanelTransparente2Layout);
        jPanelTransparente2Layout.setHorizontalGroup(
            jPanelTransparente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelTransparente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTransparente2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JLabel_Registro)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelTransparente2Layout.setVerticalGroup(
            jPanelTransparente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(jPanelTransparente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTransparente2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JLabel_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelTransparente1.add(jPanelTransparente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 80, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("x");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanelTransparente1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 20, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jEImagePanel1.add(jPanelTransparente1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PasswordKeyTyped

        char tecla = evt.getKeyChar();
        if (KeyEvent.VK_ENTER == tecla) {
            JLabel_LoginMouseClicked(null);
        }
    }//GEN-LAST:event_txt_PasswordKeyTyped

    private void JLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabel_LoginMouseClicked

        try {
            usuario = txt_Usuario.getText();
            password = txt_Password.getText();

            String mensaje = "Login " + usuario + " " + cifrarBase64(password) + " ";
            byte datos[] = mensaje.getBytes();
            JOptionPane.showMessageDialog(null, mensaje);
            //crear enviarPaquete

            DatagramPacket snd = ip.Direccion(datos);
            socket.send(snd);//enviar paquete

            this.setVisible(false);
        } catch (IOException exceptionES) {
            exceptionES.printStackTrace();
        }
        try {
            socket = new DatagramSocket();
        } catch (SocketException excepcionSocket) {
            excepcionSocket.printStackTrace();
            System.exit(1);
        }
    }//GEN-LAST:event_JLabel_LoginMouseClicked

    private void JLabel_RegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabel_RegistroMouseClicked

        Cliente4 cliente = new Cliente4();
        cliente.setVisible(true);

    }//GEN-LAST:event_JLabel_RegistroMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public static String cifrarBase64(String a) {
        Base64.Encoder encoder = Base64.getEncoder();
        String b = encoder.encodeToString(a.getBytes(StandardCharsets.UTF_8));
        return b;
    }

    public static String descifrarBase64(String a) {
        Base64.Decoder decoder = Base64.getDecoder();
        byte[] decodedByteArray = decoder.decode(a);

        String b = new String(decodedByteArray);
        return b;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_Login;
    private javax.swing.JLabel JLabel_Registro;
    private LIB.JPanelRound JPanel_Login;
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private LIB.JPanelTransparente jPanelTransparente1;
    private LIB.JPanelTransparente jPanelTransparente2;
    private LIB.JTexfieldPH_Password txt_Password;
    private LIB.JTexfieldPH_FielTex txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
