
import DTO.Clientes_DTO;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author reyes
 */
public class PrincipalForm extends javax.swing.JFrame implements Runnable {

    Clientes_DTO dto;
    Conexion conn;

    String nombre_Cliente;
    String buscar_Clientes;

    private DatagramSocket socket;
    Direccion_IP ip = new Direccion_IP();

    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;

    public PrincipalForm() {
        try {
            initComponents();

            socket = new DatagramSocket();
            dto = new Clientes_DTO();
            conn = new Conexion();

            setLocationRelativeTo(null);
            setTitle("Sistema Bancario");

            groupSexo_Cliente.add(rad_Masculino);
            groupSexo_Cliente.add(rad_Femenino);

            h1 = new Thread(this);
            h1.start();

            txt_id_cliente.setVisible(false);
        } catch (SocketException ex) {
            Logger.getLogger(PrincipalForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public String sexo_Cliente() {

        String sexo = "";

        if (rad_Masculino.isSelected()) {

            sexo = "Masculino";

        } else if (rad_Femenino.isSelected()) {

            sexo = "Femenino";

        }

        return sexo;

    }

    private void eventos(DefaultMutableTreeNode nodo) {

        try {

            if (nodo.getUserObject().equals("Cuenta")) {

            }
            if (nodo.getUserObject().equals("Agregar Nuevo Cliente")) {

                JTabbedPrincipal.setSelectedIndex(1);

            }
            if (nodo.getUserObject().equals("Bancos")) {

            }
            if (nodo.getUserObject().equals("Empresas")) {

            }
            if (nodo.getUserObject().equals("Seguros")) {

            }
        } catch (NullPointerException e) {
        }
    }

    public void limpiar_Campos(JTextField campo) {

        campo.setText("");

    }

    public void limpar_Cliente() {

        limpiar_Campos(txt_Nombre);
        limpiar_Campos(txt_Ap_Paterno);
        limpiar_Campos(txt_Ap_Materno);
        limpiar_Campos(txt_Direccion);
        limpiar_Campos(txt_Email);
        limpiar_Campos(txt_Telefono);
        limpiar_Campos(txt_nombre_Buscar);

        groupSexo_Cliente.clearSelection();

        combo_Pais.setSelectedIndex(0);
        combo_Tipo_Cuenta.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSexo_Cliente = new javax.swing.ButtonGroup();
        JTabbedPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree_Inicio = new javax.swing.JTree();
        btn_movimientos = new javax.swing.JButton();
        btn_estadoCuenta = new javax.swing.JButton();
        btn_nomina = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JLabel_Hora = new javax.swing.JLabel();
        JPanelClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Nuevo_Cliente = new javax.swing.JButton();
        btn_Guardar_Cliente = new javax.swing.JButton();
        btn_Buscar_Cliente = new javax.swing.JButton();
        btn_Cancelar_Cliente = new javax.swing.JButton();
        btn_Eliminar_Cliente = new javax.swing.JButton();
        txt_Email = new javax.swing.JTextField();
        txt_nombre_Buscar = new javax.swing.JTextField();
        txt_Ap_Paterno = new javax.swing.JTextField();
        txt_Ap_Materno = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rad_Femenino = new javax.swing.JRadioButton();
        rad_Masculino = new javax.swing.JRadioButton();
        combo_Tipo_Cuenta = new javax.swing.JComboBox<>();
        combo_Pais = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        btn_Editar_Cliente = new javax.swing.JButton();
        txt_id_cliente = new javax.swing.JTextField();
        JPanel_Usuarios = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new ImageIcon(getClass().getResource("/img/icono3.jpg")).getImage());

        JTabbedPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel11.setText("Bienvenido(a) a Nuestro Sistema Bancario");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 220, 450, 27);

        JTree_Inicio.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Inicio");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cuenta");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ver Estado de Cuenta");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Movimientos");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agregar Nuevo Cliente");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Bancos");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agregar Nuevo Banco");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agregar Nueva Empresa");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ver Nomina");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Seguros");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agregar Nuevo Seguro");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ver Seguros");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        JTree_Inicio.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTree_InicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTree_Inicio);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1, 1, 220, 504);

        btn_movimientos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_movimientos.setText("Movimientos de Cuenta");
        jPanel1.add(btn_movimientos);
        btn_movimientos.setBounds(400, 300, 200, 40);

        btn_estadoCuenta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_estadoCuenta.setText("Estado de Cuenta");
        jPanel1.add(btn_estadoCuenta);
        btn_estadoCuenta.setBounds(400, 370, 200, 40);

        btn_nomina.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btn_nomina.setText("Nomina");
        jPanel1.add(btn_nomina);
        btn_nomina.setBounds(400, 440, 200, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono2 - copia.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 40, 190, 150);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/une.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(720, 10, 60, 50);

        JLabel_Hora.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jPanel1.add(JLabel_Hora);
        JLabel_Hora.setBounds(640, 480, 140, 20);

        JTabbedPrincipal.addTab("Menu", jPanel1);

        JPanelClientes.setBackground(new java.awt.Color(255, 255, 255));
        JPanelClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        JPanelClientes.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por Nombre:");
        JPanelClientes.add(jLabel1);
        jLabel1.setBounds(440, 30, 130, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ap Paterno:");
        JPanelClientes.add(jLabel2);
        jLabel2.setBounds(100, 160, 73, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ap Materno:");
        JPanelClientes.add(jLabel3);
        jLabel3.setBounds(100, 240, 76, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Direccion:");
        JPanelClientes.add(jLabel4);
        jLabel4.setBounds(100, 290, 61, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Telefono:");
        JPanelClientes.add(jLabel5);
        jLabel5.setBounds(100, 330, 58, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email:");
        JPanelClientes.add(jLabel6);
        jLabel6.setBounds(440, 200, 38, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Pais:");
        JPanelClientes.add(jLabel7);
        jLabel7.setBounds(440, 120, 29, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tipo de Cliente:");
        JPanelClientes.add(jLabel8);
        jLabel8.setBounds(440, 160, 96, 17);

        btn_Nuevo_Cliente.setText("Nuevo");
        btn_Nuevo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Nuevo_ClienteActionPerformed(evt);
            }
        });
        JPanelClientes.add(btn_Nuevo_Cliente);
        btn_Nuevo_Cliente.setBounds(120, 420, 63, 23);

        btn_Guardar_Cliente.setText("Guardar");
        btn_Guardar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Guardar_ClienteActionPerformed(evt);
            }
        });
        JPanelClientes.add(btn_Guardar_Cliente);
        btn_Guardar_Cliente.setBounds(240, 420, 71, 23);

        btn_Buscar_Cliente.setText("Buscar");
        btn_Buscar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Buscar_ClienteActionPerformed(evt);
            }
        });
        JPanelClientes.add(btn_Buscar_Cliente);
        btn_Buscar_Cliente.setBounds(700, 20, 70, 30);

        btn_Cancelar_Cliente.setText("Cancelar");
        btn_Cancelar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancelar_ClienteActionPerformed(evt);
            }
        });
        JPanelClientes.add(btn_Cancelar_Cliente);
        btn_Cancelar_Cliente.setBounds(360, 420, 80, 23);

        btn_Eliminar_Cliente.setText("Eliminar");
        btn_Eliminar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Eliminar_ClienteActionPerformed(evt);
            }
        });
        JPanelClientes.add(btn_Eliminar_Cliente);
        btn_Eliminar_Cliente.setBounds(600, 420, 73, 23);

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPanelClientes.add(txt_Email);
        txt_Email.setBounds(540, 190, 190, 30);

        txt_nombre_Buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPanelClientes.add(txt_nombre_Buscar);
        txt_nombre_Buscar.setBounds(570, 20, 120, 30);

        txt_Ap_Paterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPanelClientes.add(txt_Ap_Paterno);
        txt_Ap_Paterno.setBounds(200, 150, 190, 30);

        txt_Ap_Materno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPanelClientes.add(txt_Ap_Materno);
        txt_Ap_Materno.setBounds(200, 190, 190, 30);

        txt_Direccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPanelClientes.add(txt_Direccion);
        txt_Direccion.setBounds(200, 280, 190, 30);

        txt_Telefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPanelClientes.add(txt_Telefono);
        txt_Telefono.setBounds(200, 320, 190, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Ap Materno:");
        JPanelClientes.add(jLabel9);
        jLabel9.setBounds(100, 200, 76, 17);

        rad_Femenino.setText("Feminino");
        JPanelClientes.add(rad_Femenino);
        rad_Femenino.setBounds(300, 240, 90, 23);

        rad_Masculino.setText("Masculino");
        JPanelClientes.add(rad_Masculino);
        rad_Masculino.setBounds(200, 240, 73, 23);

        combo_Tipo_Cuenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_Tipo_Cuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Premier" }));
        JPanelClientes.add(combo_Tipo_Cuenta);
        combo_Tipo_Cuenta.setBounds(540, 150, 190, 30);

        combo_Pais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_Pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Argentina", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bangladés", "Barbados", "Baréin", "Bélgica", "Belice", "Benín", "Bielorrusia", "Birmania", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Ciudad del Vaticano", "Colombia", "Comoras", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica", "Croacia", "Cuba", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guyana", "Guinea", "Guinea ecuatorial", "Guinea-Bisáu", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia", "Islas Marshall", "Islas Salomón", "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Centroafricana", "República Checa", "República del Congo", "República Democrática del Congo", "República Dominicana", "República Sudafricana", "Ruanda", "Rumanía", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uruguay", "Uzbekistán", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Yibuti", "Zambia", "Zimbabue" }));
        JPanelClientes.add(combo_Pais);
        combo_Pais.setBounds(540, 110, 190, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nombre:");
        JPanelClientes.add(jLabel10);
        jLabel10.setBounds(100, 120, 54, 17);

        txt_Nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPanelClientes.add(txt_Nombre);
        txt_Nombre.setBounds(200, 110, 190, 30);

        btn_Editar_Cliente.setText("Editar");
        btn_Editar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Editar_ClienteActionPerformed(evt);
            }
        });
        JPanelClientes.add(btn_Editar_Cliente);
        btn_Editar_Cliente.setBounds(490, 420, 61, 23);
        JPanelClientes.add(txt_id_cliente);
        txt_id_cliente.setBounds(200, 70, 100, 30);

        JTabbedPrincipal.addTab("Clientes", JPanelClientes);

        JPanel_Usuarios.setBackground(new java.awt.Color(255, 255, 255));
        JPanel_Usuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        JPanel_Usuarios.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Gustavo");
        JPanel_Usuarios.add(jLabel14);
        jLabel14.setBounds(16, 30, 50, 17);

        jLabel17.setText("ID");
        JPanel_Usuarios.add(jLabel17);
        jLabel17.setBounds(27, 73, 11, 14);
        JPanel_Usuarios.add(jTextField1);
        jTextField1.setBounds(90, 70, 140, 20);

        JTabbedPrincipal.addTab("Usuarios", JPanel_Usuarios);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuentas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Job");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(719, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );

        JTabbedPrincipal.addTab("Cuentas", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Luis");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(743, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        JTabbedPrincipal.addTab("Movimientos", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empresas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Beth");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(377, Short.MAX_VALUE))
        );

        JTabbedPrincipal.addTab("Empresas", jPanel6);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Reyes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(717, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(468, Short.MAX_VALUE))
        );

        JTabbedPrincipal.addTab("Banco", jPanel3);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nominas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        JTabbedPrincipal.addTab("Nominas", jPanel7);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seguros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        JTabbedPrincipal.addTab("Seguros", jPanel2);

        getContentPane().add(JTabbedPrincipal, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Guardar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Guardar_ClienteActionPerformed

        try {

            String ap_Paterno;
            String ap_Materno;
            String sexo;
            String direccion;
            String telefono;
            String email;
            String pais;
            String tipo_cuenta;

            nombre_Cliente = txt_Nombre.getText().trim();
            ap_Paterno = txt_Ap_Paterno.getText().trim();
            ap_Materno = txt_Ap_Materno.getText().trim();
            sexo = sexo_Cliente();
            direccion = txt_Direccion.getText().trim();
            email = txt_Email.getText().trim();
            telefono = txt_Telefono.getText().trim();
            pais = combo_Pais.getSelectedItem().toString();
            tipo_cuenta = combo_Tipo_Cuenta.getSelectedItem().toString();

            String mensaje = "NewCliente " + nombre_Cliente + " " + ap_Paterno + " " + ap_Materno + " " + sexo + " " + direccion + " " + email + " " + telefono + " " + pais + " " + tipo_cuenta + " ";
            byte datos[] = mensaje.getBytes();
            JOptionPane.showMessageDialog(null, mensaje);
            //crear enviarPaquete

            DatagramPacket snd = ip.Direccion(datos);
            socket.send(snd);//enviar paquete

        } catch (IOException exceptionES) {
            exceptionES.printStackTrace();
        }
        try {
            socket = new DatagramSocket();
        } catch (SocketException excepcionSocket) {
            excepcionSocket.printStackTrace();
            System.exit(1);
        }

    }//GEN-LAST:event_btn_Guardar_ClienteActionPerformed

    private void JTree_InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTree_InicioMouseClicked

        if (evt.getClickCount() == 2) {

            DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) JTree_Inicio.getLastSelectedPathComponent();
            eventos(nodoSeleccionado);
        }
    }//GEN-LAST:event_JTree_InicioMouseClicked

    private void btn_Nuevo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Nuevo_ClienteActionPerformed

        int a = JOptionPane.showConfirmDialog(this, "Estas Seguro de Limpiar los Campos?");
        if (JOptionPane.OK_OPTION == a) {
            limpar_Cliente();

        } else {

        }

    }//GEN-LAST:event_btn_Nuevo_ClienteActionPerformed

    private void btn_Cancelar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancelar_ClienteActionPerformed

        int a = JOptionPane.showConfirmDialog(this, "Estas Seguro de Cancelar?");
        if (JOptionPane.OK_OPTION == a) {
            limpar_Cliente();
            JTabbedPrincipal.setSelectedIndex(0);

        } else {

        }

    }//GEN-LAST:event_btn_Cancelar_ClienteActionPerformed

    private void btn_Editar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Editar_ClienteActionPerformed

        int a = JOptionPane.showConfirmDialog(this, "Estas Seguro de Editar el Cliente?");
        if (JOptionPane.OK_OPTION == a) {

            try {

                String id_cliente;
                String ap_Paterno;
                String ap_Materno;
                String sexo;
                String direccion;
                String telefono;
                String email;
                String pais;
                String tipo_cuenta;

                id_cliente = txt_id_cliente.getText().trim();
                nombre_Cliente = txt_Nombre.getText().trim();
                ap_Paterno = txt_Ap_Paterno.getText().trim();
                ap_Materno = txt_Ap_Materno.getText().trim();
                sexo = sexo_Cliente();
                direccion = txt_Direccion.getText().trim();
                email = txt_Email.getText().trim();
                telefono = txt_Telefono.getText().trim();
                pais = combo_Pais.getSelectedItem().toString();
                tipo_cuenta = combo_Tipo_Cuenta.getSelectedItem().toString();

                String mensaje = "EditCliente " + id_cliente + " " + nombre_Cliente + " " + ap_Paterno + " " + ap_Materno + " " + sexo + " " + direccion + " " + email + " " + telefono + " " + pais + " " + tipo_cuenta + " ";
                byte datos[] = mensaje.getBytes();
                JOptionPane.showMessageDialog(null, mensaje);
                //crear enviarPaquete

                DatagramPacket snd = ip.Direccion(datos);
                socket.send(snd);//enviar paquete

            } catch (IOException exceptionES) {
                exceptionES.printStackTrace();
            }
            try {
                socket = new DatagramSocket();
            } catch (SocketException excepcionSocket) {
                excepcionSocket.printStackTrace();
                System.exit(1);
            }

        } else {

        }

    }//GEN-LAST:event_btn_Editar_ClienteActionPerformed

    private void btn_Eliminar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Eliminar_ClienteActionPerformed

        int a = JOptionPane.showConfirmDialog(this, "Estas Seguro de Eliminar el Cliente?");
        if (JOptionPane.OK_OPTION == a) {

            try {
                String id_clientes;
                id_clientes = txt_id_cliente.getText();
                String mensaje = "DeleteCliente " + id_clientes + " Registro Borrado";
                byte datos[] = mensaje.getBytes();
                //crear enviarPaquete

                DatagramPacket snd = ip.Direccion(datos);
                socket.send(snd);//enviar paquete
            } catch (IOException exceptionES) {
                exceptionES.printStackTrace();
            }
            try {
                socket = new DatagramSocket();
            } //atrapar los problemas que puedan ocurrir al crear objeto DatagramSocket
            catch (SocketException excepcionSocket) {
                excepcionSocket.printStackTrace();
                System.exit(1);
            }

        } else {

        }

    }//GEN-LAST:event_btn_Eliminar_ClienteActionPerformed

    private void btn_Buscar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Buscar_ClienteActionPerformed

        if (txt_nombre_Buscar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el Nombre para Buscar!", "Campo Vacio", JOptionPane.WARNING_MESSAGE);
            txt_nombre_Buscar.requestFocus();

        } else {

            try {
                //obtener mensaje del campo de texto y convertirlo en arrreglo byte
                buscar_Clientes = txt_nombre_Buscar.getText().trim();
                String mensaje = "SearchCliente" + " " + buscar_Clientes + " ";
                byte datos[] = mensaje.getBytes();
//          //crear enviarPaquete

                DatagramPacket snd = ip.Direccion(datos);
                socket.send(snd);
                //enviar paquete
            } catch (IOException exceptionES) {
                exceptionES.printStackTrace();
            }
            try {
                esperarPaquetesClientes();
                socket = new DatagramSocket();

            } catch (SocketException excepcionSocket) {
                excepcionSocket.printStackTrace();
                System.exit(1);
            }

        }

    }//GEN-LAST:event_btn_Buscar_ClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == h1) {
            calcula();
            JLabel_Hora.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }

    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();

        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";

        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    private void esperarPaquetesClientes() {
        try {
            //establecer el paquete
            byte datos[] = new byte[100];
            DatagramPacket recibirPaquete = new DatagramPacket(
                    datos, datos.length);
            socket.receive(recibirPaquete);//esperar un paquete
            String cad = (new String(recibirPaquete.getData(),
                    0, recibirPaquete.getLength()));
            String[] variables;
            variables = cad.split(" ");

            txt_id_cliente.setText(variables[0]);
            txt_Nombre.setText(variables[1]);
            txt_Ap_Paterno.setText(variables[2]);
            txt_Ap_Materno.setText(variables[3]);

            if (variables[4].equals("Masculino")) {

                rad_Masculino.setSelected(true);

            } else {

                rad_Femenino.setSelected(true);

            }

            txt_Direccion.setText(variables[5]);
            txt_Telefono.setText(variables[6]);
            txt_Email.setText(variables[7]);
            combo_Pais.setSelectedItem(variables[8]);
            combo_Tipo_Cuenta.setSelectedItem(variables[9]);

        } catch (IOException excepcion) {
            excepcion.printStackTrace();
        }
    }//fin del metodo e

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_Hora;
    private javax.swing.JPanel JPanelClientes;
    private javax.swing.JPanel JPanel_Usuarios;
    private javax.swing.JTabbedPane JTabbedPrincipal;
    private javax.swing.JTree JTree_Inicio;
    private javax.swing.JButton btn_Buscar_Cliente;
    private javax.swing.JButton btn_Cancelar_Cliente;
    private javax.swing.JButton btn_Editar_Cliente;
    private javax.swing.JButton btn_Eliminar_Cliente;
    private javax.swing.JButton btn_Guardar_Cliente;
    private javax.swing.JButton btn_Nuevo_Cliente;
    private javax.swing.JButton btn_estadoCuenta;
    private javax.swing.JButton btn_movimientos;
    private javax.swing.JButton btn_nomina;
    private javax.swing.JComboBox<String> combo_Pais;
    private javax.swing.JComboBox<String> combo_Tipo_Cuenta;
    private javax.swing.ButtonGroup groupSexo_Cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rad_Femenino;
    private javax.swing.JRadioButton rad_Masculino;
    private javax.swing.JTextField txt_Ap_Materno;
    private javax.swing.JTextField txt_Ap_Paterno;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_nombre_Buscar;
    // End of variables declaration//GEN-END:variables
}
